### ISSUE TITLE
BBC Connected Studio - mobile storytelling

### ISSUE THREAD

**Issue by robertocarroll** [wearethoughtfox/wearethoughtfox-wp#38]
The BBC Connected Studio Mobile Storytelling brief was released yesterday.  I'll put it in Slack. The closing date is 16 October.

**Comment by clintmclean** [comment]
Hi, Ok I read through most of it and will finish reading when we get to
Jerez later today.
Will start thinking of possible ideas. ...the zombie fitness app is pretty
neat.

C.

**Comment by robertocarroll** [comment]
So here's what I've got so far: 

The medium is text message. Once a day you can text something that you love from the BBC - can be anything from news to sport to programmes - and in return you get a text back with a recommendation from someone else. 

You can put a reason in the text message why you are sharing it, but it can only be text message length. 

Clearly owes a lot to https://this.cm/ but it also picks up on some of the stuff mentioned here: http://www.mattmcalister.com/blog/2015/06/08/1993/the-future-is-privileged-information/

Text message means there's no app or anything to download and it's also private and a different space to explore. 

There's lots you could do - did you like it? Why not? Then it could be taken further - what if it was also about the connection with the person who shared it? "Creating conversations when different people see different things" (from the brief). 

It's not quite there ... but there might be something it in. Thoughts?

**Comment by robertocarroll** [comment]
![photo](https://cloud.githubusercontent.com/assets/1565953/10452658/42ac59a2-719e-11e5-8cba-3b3cf5f1fd50.JPG)

**Comment by clintmclean** [comment]
Hi - I like the sms-based idea and the idea of community and exchange.
The problem I see with the BBC though is that their content is not really aimed at these people and I think first and foremost the content has to appeal to them and not just the delivery of the content.
I know we're not being asked to programme the BBC so it makes this a bit tricky. A 24 year old wants to see their peers involved in the shows they watch and maybe that's why VICE News has taken off among that segment - they don't look like typical newscasters.

My thinking has been along the lines of how to include them in the content and I've been thinking along the lines of university newspapers. There are a lot of very good ones and while it would obviously require oversight and editor involvement from the BBC - the content would be produced by the market they are targeting. 

How would it work:
Participating schools and their newspaper editors submit their best stories to BBC on a regular basis.
Stories are uploaded flipboard style and sit in their own subsection within the BBC domain but designed with smarkphone and ipad use as their intended.
BBC selects a dozen or so stories a day and upload them.
Young readers read them and give them a thumbs up or down and have the content rise or fall depending on the votes. Comments are encouraged and readers could have user names and icons so they are not anonymous.

**Comment by clintmclean** [comment]
I'm not sure if our ideas work together or how much mine is even worth working over.
It requires schools to organized etc and probably a payment system for the articles (though that shouldn't really be a problem as news outlets pay for content anyway so...

What do you think? Worth trying to merge the two ideas or are they not connected enough?

**Comment by robertocarroll** [comment]
The issues I see with the newspaper idea is that it doesn't really tick the innovation box, is content-intensive and steps into territory which the BBC isn't involved in (very local stuff). I can't remember the details but I read something a while ago about just how specific and local the BBC is allowed to go so it doesn't kill off local newspapers etc. 

Perhaps they could work together if one of the outputs of the SMS thing was a newspaper which included the conversations around the content. It wouldn't get to heart of the problem you outline but it would but an interesting thing to explore - a newspaper created by users purely from text messages with reference to BBC content.

**Comment by clintmclean** [comment]
Yeah fair enough. The idea is certainly more based around the content - I don't think i'm knowledgable enough in tech innovation to think 'innovation first'.
I like the sms idea - to me the problem though is still the content. Just because the target segment can interact with the content on their smart phones, do they want to if the content isn't something that speaks to them? How can that be treated to make it more appealing?
I keep thinking of the zombie run app in the BBC examples and it is a really clever approach to making running - something that is virtually the same for everyone and has been forever - and creating a way to make it different for a group of people through an app. The content itself hasn't changed - it is still running - but the experience is brand new.

**Comment by greatmisschris** [comment]
Hi Rob - not found my way into this space before...! I've read through the BBC storytelling call. My first thoughts were around proximity - proximity to a story which can be measured in a whole range of ways (geographic, personal, emotional, age, gender etc etc). Some are objective (geographic, age, gender) which could be linked to a profile, others much more subjective but could equally provide interesting insight into storytelling (like how upset/moved/amused/horrified you are by a story). I often think it is interesting when you look at the most read stories on the BBC, but sometimes its not clear why people are attracted to them. This might fit in with your text idea or blue tooth/GPS

**Comment by robertocarroll** [comment]
Submitted. The final proposal is BBC storytelling pitch in the shared Google Drive. Closing this issue.
